[package]
name = "watchmate"
version = "0.4.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
infinitime = { path = "../infinitime", features = ["freedesktop", "github"] }
relm4 = { git = "https://github.com/Relm4/relm4", branch = "next", features = ["libadwaita", "gnome_43"] }
relm4-components = { git = "https://github.com/Relm4/relm4", branch = "next" }
futures = "0.3"
anyhow = "1.0"
version-compare = "0.1"
log = "0.4"
env_logger = "0.10"
